from typing import Protocol, Optional
from uuid import UUID
from datetime import datetime

from app.domain.entities.auction import Auction
from app.domain.entities.bid import Bid
from app.domain.entities.user import User


class UserRepository(Protocol):
    def save(self, user: User) -> None: ...
    def get_by_id(self, user_id: UUID) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...


class BidRepository(Protocol):
    def save(self, bid: Bid) -> None: ...
    def get_by_auction_id(self, auction_id: UUID) -> list[Bid]: ...



class AuctionRepository(Protocol):
    def save(self, auction: Auction) -> None: ...
    def get_by_id(self, auction_id: UUID) -> Optional[Auction]: ...
    def get_active_expired(self, current_time: datetime) -> list[Auction]: ...