from typing import Protocol
from uuid import UUID
from datetime import datetime

from app.domain.entities.auction import Auction
from app.domain.entities.bid import Bid
from app.domain.entities.user import User


class UserRepository(Protocol):
    def save(self, user: User) -> User: ...
    def find_by_id(self, user_id: UUID) -> User: ...
    def find_by_email(self, email: str) -> User: ...


class BidRepository(Protocol):
    def save(self, bid: Bid) -> Bid: ...
    def find_by_auction_id(self, auction_id: UUID) -> list[Bid]: ...



class AuctionRepository(Protocol):
    def save(self, auction: Auction) -> Auction: ...
    def find_by_id(self, auction_id: UUID) -> Auction: ...
    def find_active_with_expired_time(self, current_time: datetime) -> list[Auction]: ...